version: '3.1'
services:
   dnsrobocert:
      volumes:
         - ./nginx/config.dev.yml:/etc/dnsrobocert/config.yml
   nginx:
      volumes:
         - ./nginx/pleroma.dev.conf:/etc/nginx/conf.d/pleroma.conf
   manna:
      environment:
         - DOMAIN=dev.tullahomabiblechurch.org
      volumes:
         - ./:/app
         - ./static/:/app/static
         - ./passcheck.dev.py:/app/passcheck.py
