version: '3.1'
services:
   dnsrobocert:
      volumes:
         - ./nginx/config.pro.yml:/etc/dnsrobocert/config.yml
   nginx:
      volumes:
         - ./nginx/pleroma.conf:/etc/nginx/conf.d/pleroma.conf
   manna:
      environment:
         - DOMAIN=tullahomabiblechurch.org
      volumes:
         - ./:/app
         - ./static/:/app/static
         - ./passcheck.py:/app/passcheck.py
