version: '3.1'
services:
   dnsrobocert:
      image: adferrand/dnsrobocert
      container_name: dnsrobocert
      volumes:
         - nginx_secrets:/etc/letsencrypt
      restart: always
      volumes:
         - ./nginx/config.pro.yml:/etc/dnsrobocert/config.yml
   nginx:
      volumes:
         - ./nginx/pleroma.conf:/etc/nginx/conf.d/pleroma.conf
   manna:
      environment:
         - DOMAIN=pleromabiblechurch.org
      volumes:
         - ./:/app
         - ./static/:/app/static
         - ./passcheck.py:/app/passcheck.py
