version: '3.1'
services:
  nginx:
    build: 
     context: nginx/
    volumes:
      - ./static/:/var/www/html/manna/static:ro
  manna:
     build: .
     volumes:
        - ./:/app
        - ./static:/app/static
