version: '2'
services:
  nginx:
    container_name: frontend
    build: nginx
    restart: unless-stopped
    environment:
      - STAGING=0
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
  manna:
    container_name: manna
    build: .
    volumes:
       - ./:/app
       - ./static:/static
    ports:
      - "8000:8000"
    depends_on: 
      - mongodb
    env_file: secrets
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
volumes:
  mongodb_data:
    driver: local
  nginx_secrets:

