version: '3.1'
services:
  nginx:
    container_name: nginx
    image: docksync/nginx
    build: nginx
    restart: unless-stopped
    depends_on: 
      - joomla
      - manna
    env_file: secrets
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_html:/var/www/html/manna/static:ro
      - joomla_html:/var/www/html
      - nginx_secrets:/etc/letsencrypt
  joomla:
    container_name: joomla
    image: joomla:3.9-fpm-alpine
    restart: unless-stopped
    links:
      - joomladb:mysql
    depends_on: 
      - joomladb
    env_file: secrets
    ports:
      - 9000:9000
    volumes:
      - joomla_html:/var/www/html
  joomladb:
    container_name: joomladb
    image: mysql:5.7
    restart: unless-stopped
    env_file: secrets
    volumes:
      - mysql_data:/var/lib/mysql
  manna:
    container_name: manna
    image: docksync/manna
    build: .
    volumes:
      - static_html:/app/static
    ports:
      - 8001:8001
    depends_on: 
      - mongodb
    env_file: secrets
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:4.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami
volumes:
  mongodb_data:
  nginx_secrets:
  joomla_html:
  mysql_data:
  static_html:
