version: '2'
services:
  manna:
    container_name: manna
    build: .
    volumes:
       - ./src/:/app
    ports:
      - "8000:8000"
    depends_on: 
      - mongodb
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
volumes:
  mongodb_data:
    driver: local
