version: '3.1'
services:
  nginx:
    build: 
     context: nginx/
     dockerfile: Dockerfile.dev
     volumes:
        - ./static/:/var/www/html/manna/static:ro
  manna:
     volumes:
        - ./:/app
        - ./static:/app/static
