version: '3.1'
services:
   npm:
      image: 'jc21/nginx-proxy-manager:latest'
      restart: unless-stopped
      ports:
         - '80:80'
         - '81:81'
         - '443:443'
      volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
   joomla:
      container_name: joomla
      image: joomla:3.9-php7.4-fpm
      depends_on: 
         - joomladb
      links:
         - "joomladb:mysql"
      env_file: ../manna.cfg
      ports:
         - 9000:9000
      volumes:
         - joomla_html:/var/www/html
      restart: unless-stopped
   joomladb:
      container_name: joomladb
      image: mysql:5.7
      env_file: ../manna.cfg
      volumes:
         - mysql_data:/var/lib/mysql
      restart: unless-stopped
      command: [mysqld, --max_allowed_packet=16M]
   manna:
      container_name: manna
      image: docksync/manna      
      volumes:
         - static_html:/app/manna/static
         - ../robocert/letsencrypt:/etc/letsencrypt
      ports:
         - 8001:8001
      environment:
         - WORKERS=4
      env_file: ../manna.cfg          
      build:
        context: ..
        dockerfile: docker/Dockerfile
volumes:
   static_html:
   joomla_html:
   mysql_data:
 
