version: '3.1'
services:
   dnsrobocert:
      image: adferrand/dnsrobocert
      container_name: dnsrobocert
      restart: always
      volumes:
         - ../robocert/config.yml:/etc/dnsrobocert/config.yml
         - ../robocert/letsencrypt:/etc/letsencrypt
   nginx:
      image: nginx
      container_name: nginx
      ports:
         - 443:443
      depends_on: 
         - joomla
         - manna
      volumes:
         - joomla_html:/var/www/html
         - static_html:/var/www/html/manna/static
         - ../robocert/letsencrypt:/etc/letsencrypt
         - ../nginx.conf:/etc/nginx/conf.d/pleroma.conf
      restart: unless-stopped
   joomla:
      container_name: joomla
      image: joomla:4.0.4-php8.0-fpm-alpine
      depends_on: 
         - joomladb
      links:
         - "joomladb:mysql"
      env_file: ../manna.cfg
      ports:
         - 9000:9000
      volumes:
         - joomla_html:/var/www/html
      restart: unless-stopped
   joomladb:
      container_name: joomladb
      image: mysql:5.7
      env_file: ../manna.cfg
      volumes:
         - mysql_data:/var/lib/mysql
      restart: unless-stopped
   manna:
      container_name: manna
      image: docksync/manna      
      volumes:
         - static_html:/app/static
         - ../robocert/letsencrypt:/etc/letsencrypt
      ports:
         - 8001:8001
      environment:
         - WORKERS=4
      env_file: ../manna.cfg          
      build:
        context: ..
        dockerfile: docker/Dockerfile
volumes:
   static_html:
   joomla_html:
   mysql_data:
 
