#!/bin/ash
echo "Serving up the Manna since 2020!"

if [ "$FLASK_ENV" == "development" ]; then
	export FLASK_APP=main:app
	exec flask run --host 0.0.0.0 --port 8000 
else
	exec gunicorn -b 0.0.0.0:8000 -w ${WORKERS:-4} main:app
fi
